### ISSUE TITLE
Unable to connect to ra-multiplex server running under systemd

### ISSUE THREAD

**Issue by stanle-cs** [pr2502/ra-multiplex#41]
What works:
- Running `ra-multiplex server` on a separate terminal.
- Connect using `coc.nvim` and `coc-rust-analyzer` with the `rust-analyzer.server.path` pointing to `ra-multiplex`

What doesn't:
- Start ra-multiplex with the example systemd service:
```
[Unit]
Description=Rust analyzer multiplex server

[Service]
Type=simple
ExecStart=/home/user/.cargo/bin/ra-multiplex server

[Install]
WantedBy=default.target
```

The service started just fine, but seems like it is unable to spawn `rust-analyzer` when started by systemd
[status_output.txt](https://github.com/pr2502/ra-multiplex/files/12709361/status_output.txt)

What did I do wrong?

Thanks!

**Comment by pr2502** [comment]
Hi, `ra-multiplex` needs to either have `rust-analyzer` somewhere in its $PATH or you need to pass it the full path to `rust-analyzer`. For `coc.nvim` that will look like:

```json
"rust-analyzer.server.extraEnv": { "RA_MUX_SERVER": "/path/to/rust-analyzer" }
```

**Comment by stanle-cs** [comment]
Thank you @pr2502, I added the above config to my CocConfig, but it did not change the outcome.

I think I need to clarify, that my ra-multiplex can find the rust-analyzer binary just fine when the server is started by hand. It will connect and run normally. Only when the server is started by systemd service that it seems to have a problem with finding rust-analyzer (no such file or directory (os error 2))

**Comment by stanle-cs** [comment]
Update: after fiddling around with it, you are right! I added
```json
"rust-analyzer.server.extraEnv": {
"RA_MUX_SERVER": "~/.cargon/bin/rust-analyzer" 
}
```
at the beginning. the multiflexer failed to spawn an ra instance.

I then changed the config to:
```json
"rust-analyzer.server.extraEnv": {
"RA_MUX_SERVER": "/home/user/.cargon/bin/rust-analyzer" 
}
```
The systemd service now function properly.

Thank you very much! This issue is resolved.

**Comment by pr2502** [comment]
That means systemd launches it in a different environment than your terminal. Check that `systemctl --user show-environment | grep PATH` contains the directory that has the `rust-analyzer` you want in it. You can import the path using `systemctl --user import-environment PATH` to set it to the same value as your terminal.

If you use the `RA_MUX_SERVER` env var on the client you have to give it an absolute path, if you pass just `rust-analyzer` it'll again search in its environment's $PATH.

**Comment by pr2502** [comment]
Ah yes. `ra-multiplex` doesn't expand the `~`, shells do that but we don't invoke a shell.
