### ISSUE TITLE
ra-multiplex lsp-config Connection refused (os error 111)

### ISSUE THREAD

**Issue by SrMrBurchick** [pr2502/ra-multiplex#43]
Hi! I'm trying to setup nvim with ra-multiplex. I've just cloned and builded ra-multiplex. Added a ra-multiplex.service with the right path to ra-multiplex. I have rust-analyzer installed in my system. But anytime when I opens the .rs file there is an error 
```
[ERROR][2023-10-02 04:27:30] .../vim/lsp/rpc.lua:734	"rpc"	"/home/user/Tools/ra-multiplex/target/release/ra-multiplex"	"stderr"	"Error: connect\n\nCaused by:\n    Connection refused (os error 111)\n"
```
What I do wrong?
Here is my lsp setup
```
require('lspconfig').rust_analyzer.setup {
    cmd = { "/home/user/Tools/ra-multiplex/target/release/ra-multiplex" },
    settings = {
        ["rust-analyzer"] = {
            check = {
                overrideCommand = {
                    "cargo",
                    "clippy",
                    "--message-format=json-diagnostic-rendered-ansi",
                    "--fix",
                    "--allow-dirty"
                }
            }
        }
        }
}

```

**Comment by pr2502** [comment]
This looks like ra-multiplex server isn't running at all.

- Have you started and enabled the service? Verify by running `systemctl --user status ra-multiplex.service`. You should see a line with something like this:
  > ```
  > ● ra-mux.service - Rust analyzer multiplex server
  >     Loaded: loaded (/home/max/.config/systemd/user/ra-mux.service; enabled; preset: enabled)
  >     Active: active (running) since Thu 2023-10-19 12:00:00; 1h ago
   Main PID: 12345 (ra-multiplex)

- If you haven't changed anything in the config ra-multiplex is listening on port 27631, you can verify by running `netstat -tln`. The output should contain:
  > ```
  > Active Internet connections (only servers)
  > Proto Recv-Q Send-Q Local Address           Foreign Address         State
  > tcp        0      0 127.0.0.1:27631         0.0.0.0:*               LISTEN
