### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by xxshady** [pr2502/ra-multiplex#52]
For some reason cwd path starts with `/c%3A`

![изображение](https://github.com/pr2502/ra-multiplex/assets/54737754/a71ceee3-f2c1-4ad4-99d8-aa9811f75d5a)

I shit-fixed it in my fork: https://github.com/xxshady/ra-multiplex/commit/6fde8c2a13244d36217d4e50be5b10af9c456eea

**Comment by SonicZentropy** [comment]
Thanks for the shit-fix, it's working great!

**Comment by pr2502** [comment]
This probably got fixed by #64, the `%3A` is percent encoded `:`. Can someone on windows confirm it's been fixed?

**Comment by ollbx** [comment]
Just tried it in Windows. The "%3A" seems to be fixed, but it still seems tripped up because of the "/" before the drive name.

![image](https://github.com/user-attachments/assets/10d56595-85db-4df1-8bcc-5122c98fd9ed)

Version 0.2.4 straight from "cargo install ra-multiplex".

**Comment by ollbx** [comment]
Also slight typo "langauge" in the error message ;-).

**Comment by pr2502** [comment]
the leading slash should be fixed by #73, which is not on crates.io yet. there has been quite a few changes since the last release so i'll do another one

**Comment by pr2502** [comment]
@ollbx i've released v0.2.5 which includes #73 (and fixes those typos) if you could test on windows. so i can finally close this issue
