### ISSUE TITLE
How to use it on lunarvim?

### ISSUE THREAD

**Issue by kaicpro** [pr2502/ra-multiplex#58]
I'm trying to add ra-multiplex to lunarvim, but I'm having difficulty

**Comment by pr2502** [comment]
hi, can you please make your question more specific? have you tried starting from the neovim configuration example? lunarvim seems to be based on neovim

**Comment by kaicpro** [comment]
Since yesterday I managed to implement ra-multiplex in lunarvim, but sometimes when I start lunarvum this error happens: 
![Screenshot_20240225_215139_Termux](https://github.com/pr2502/ra-multiplex/assets/68879185/c6711751-53ac-494e-80e0-f184af77656b)
And another error also shows, as if ra-multiplex had responded to an `end` message with a `begjn`

**Comment by kaicpro** [comment]
Hi, continuing to say that I managed to resolve this bug by changing these lines in ra-multiplex's config.toml: 
```toml
instance_timeout = false
gc_interval = 1 # every 10 seconds
```

**Comment by pr2502** [comment]
Oh, that's interesting. Thanks for mentioning that, it might suggest some other issues with handling connects which lunarvim is more sensitive to than other editors.
