### ISSUE TITLE
ra-multiplex on nvim with rust-tools.nvim

### ISSUE THREAD

**Issue by tonyalaribe** [pr2502/ra-multiplex#8]
I couldnt get this to work and wasn't sure what steps to take to investigate. 
Running the `ra-multiplex-server ` doesn't read the config in my home directory (~/config/ra-multiplex/config.toml)
```
❯ ra-multiplex-server -h
[WARN ] cannot load config: cannot read config file `/Users/tonyalaribe.parity/Library/Application Support/ra-multiplex/config.toml`

    Caused by:
        No such file or directory (os error 2)
^C

```

**Comment by pr2502** [comment]
From readme

> Configuration is stored in a TOML file in your system's default configuration directory, for example `~/.config/ra-multiplex/config.toml`.

ra-multiplex is using the [directories](https://crates.io/crates/directories) crate to determine your system's default configuration directory, the `~/.config/...` path is just an example that happens to be the default on linux.

You seem to be running MacOS and for your system the default configuration directory is `/Users/<username>/Library/Application Support/ra-multiplex/config.toml`. Just move your configuration file to the appropriate path where the error message says it's expecting it.
